package practica2020;
// Generated 10-dic-2020 12:37:10 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Vacuna generated by hbm2java
 */
public class Vacuna implements java.io.Serializable {

	private char codTipo;
	private String denoTipo;
	private String laboratorio;
	private String pais;
	private Set voluntarioses = new HashSet(0);

	public Vacuna() {
	}

	public Vacuna(char codTipo) {
		this.codTipo = codTipo;
	}

	public Vacuna(char codTipo, String denoTipo, String laboratorio, String pais, Set voluntarioses) {
		this.codTipo = codTipo;
		this.denoTipo = denoTipo;
		this.laboratorio = laboratorio;
		this.pais = pais;
		this.voluntarioses = voluntarioses;
	}

	public char getCodTipo() {
		return this.codTipo;
	}

	public void setCodTipo(char codTipo) {
		this.codTipo = codTipo;
	}

	public String getDenoTipo() {
		return this.denoTipo;
	}

	public void setDenoTipo(String denoTipo) {
		this.denoTipo = denoTipo;
	}

	public String getLaboratorio() {
		return this.laboratorio;
	}

	public void setLaboratorio(String laboratorio) {
		this.laboratorio = laboratorio;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set getVoluntarioses() {
		return this.voluntarioses;
	}

	public void setVoluntarioses(Set voluntarioses) {
		this.voluntarioses = voluntarioses;
	}

}
