package practica2020;
// Generated 10-dic-2020 12:37:10 by Hibernate Tools 5.4.21.Final

/**
 * VoluntariosId generated by hbm2java
 */
public class VoluntariosId implements java.io.Serializable {

	private int codVolun;
	private char tipo;

	public VoluntariosId() {
	}

	public VoluntariosId(int codVolun, char tipo) {
		this.codVolun = codVolun;
		this.tipo = tipo;
	}

	public int getCodVolun() {
		return this.codVolun;
	}

	public void setCodVolun(int codVolun) {
		this.codVolun = codVolun;
	}

	public char getTipo() {
		return this.tipo;
	}

	public void setTipo(char tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VoluntariosId))
			return false;
		VoluntariosId castOther = (VoluntariosId) other;

		return (this.getCodVolun() == castOther.getCodVolun()) && (this.getTipo() == castOther.getTipo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodVolun();
		result = 37 * result + this.getTipo();
		return result;
	}

}
